src/Entity/CRUD.php
<?php

namespace App\Entity;

use App\Repository\CRUDRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CRUDRepository::class)
 */
class CRUD
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }
}

src/Entity/Form.php
<?php

namespace App\Entity;

use App\Repository\FormRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
/**
 * @ORM\Entity(repositoryClass=FormRepository::class)
 */
class Form
{
    /**

     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)

     */
    private $name;

    /**


     * @ORM\Column(type="string", length=255)
     */
    private $username;
    #[Assert\Type(
        type: 'integer',
        message: 'The value {{ value }} is not a valid {{ type }}.',
    )]
    /**

     * @Assert\Type(
     *     type="integer",
     *     message="The value {{ value }} is not a valid {{ type }}."
     * )
     * @ORM\Column(type="integer")
     */
    private $phone_number;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getPhoneNumber(): ?int
    {
        return $this->phone_number;
    }

    public function setPhoneNumber(int $phone_number): self
    {
        $this->phone_number = $phone_number;

        return $this;
    }
}

src/Form/CRUDType.php
<?php

namespace App\Form;

use App\Entity\CRUD;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CRUDType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => CRUD::class,
        ]);
    }
}

src/Controller/CRUDController.php
<?php

namespace App\Controller;

use App\Entity\Information;
use App\Form\InformationType;
use App\Repository\InformationRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/c/r/u/d')]
class CRUDController extends AbstractController
{
    #[Route('/', name: 'c_r_u_d_index', methods: ['GET'])]
    public function index(InformationRepository $informationRepository): Response
    {
        return $this->render('crud/index.html.twig', [
            'information' => $informationRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'c_r_u_d_new', methods: ['GET', 'POST'])]
    public function new(Request $request): Response
    {
        $information = new Information();
        $form = $this->createForm(InformationType::class, $information);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($information);
            $entityManager->flush();

            return $this->redirectToRoute('c_r_u_d_index');
        }

        return $this->render('crud/new.html.twig', [
            'information' => $information,
            'form' => $form->createView(),
        ]);
    }

    #[Route('/{id}', name: 'c_r_u_d_show', methods: ['GET'])]
    public function show(Information $information): Response
    {
        return $this->render('crud/show.html.twig', [
            'information' => $information,
        ]);
    }

    #[Route('/{id}/edit', name: 'c_r_u_d_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Information $information): Response
    {
        $form = $this->createForm(InformationType::class, $information);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('c_r_u_d_index');
        }

        return $this->render('crud/edit.html.twig', [
            'information' => $information,
            'form' => $form->createView(),
        ]);
    }

    #[Route('/{id}', name: 'c_r_u_d_delete', methods: ['POST'])]
    public function delete(Request $request, Information $information): Response
    {
        if ($this->isCsrfTokenValid('delete'.$information->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($information);
            $entityManager->flush();
        }

        return $this->redirectToRoute('c_r_u_d_index');
    }
}

templates/crud/_delete_form.html.twig
<form method="post" action="{{ path('c_r_u_d_delete', {'id': information.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ information.id) }}">
    <button class="btn">Delete</button>
</form>

templates/crud/_form.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Information{% endblock %}

{% block body %}

{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/crud/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Information{% endblock %}

{% block body %}
    <h1>Edit Information</h1>

    {{ include('c_r_u_d/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('c_r_u_d_index') }}">back to list</a>

    {{ include('c_r_u_d/_delete_form.html.twig') }}
{% endblock %}

templates/crud/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Information index{% endblock %}

{% block body %}
    <h1>Information index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>PhoneNumber</th>
                <th>IdNumber</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for information in information %}
            <tr>
                <td>{{ information.id }}</td>
                <td>{{ information.Name }}</td>
                <td>{{ information.phoneNumber }}</td>
                <td>{{ information.idNumber }}</td>
                <td>
                    <a href="{{ path('c_r_u_d_show', {'id': information.id}) }}">show</a>
                    <a href="{{ path('c_r_u_d_edit', {'id': information.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('c_r_u_d_new') }}">Create new</a>
{% endblock %}

templates/crud/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Information{% endblock %}

{% block body %}
    <h1>Create new Information</h1>

    {{ include('c_r_u_d/_form.html.twig') }}

    <a href="{{ path('c_r_u_d_index') }}">back to list</a>
{% endblock %}

templates/crud/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Information{% endblock %}

{% block body %}
    <h1>Information</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ information.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ information.Name }}</td>
            </tr>
            <tr>
                <th>PhoneNumber</th>
                <td>{{ information.phoneNumber }}</td>
            </tr>
            <tr>
                <th>IdNumber</th>
                <td>{{ information.idNumber }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('c_r_u_d_index') }}">back to list</a>

    <a href="{{ path('c_r_u_d_edit', {'id': information.id}) }}">edit</a>

    {{ include('c_r_u_d/_delete_form.html.twig') }}
{% endblock %}